# Generated by Django 6.1.1 on 2026-10-05 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('key', models.CharField(help_text="Stable key used by the 3D renderer, e.g. 'seat'", max_length=40)),
                ('help_text', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('tagline', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(default='Signature', max_length=60)),
                ('model_type', models.CharField(choices=[('chair', 'Lounge Chair'), ('mug', 'Ceramic Mug'), ('bottle', 'Water Bottle'), ('lamp', 'Desk Lamp')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('featured', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, max_length=40)),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=2)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(help_text='Primary hex color, e.g. #C75B39', max_length=9)),
                ('color2', models.CharField(blank=True, help_text='Optional secondary hex for two-tone finishes', max_length=9)),
                ('material', models.CharField(choices=[('fabric', 'Fabric'), ('leather', 'Leather'), ('plastic', 'Plastic'), ('metal', 'Metal'), ('wood', 'Wood'), ('ceramic', 'Ceramic'), ('glass', 'Glass'), ('rubber', 'Rubber')], default='plastic', max_length=20)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.part')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='catalog.product'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('product', 'key')},
        ),
    ]
