# Generated by Django 6.1.1 on 2026-10-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_type',
            field=models.CharField(choices=[('chair', 'Lounge Chair'), ('mug', 'Ceramic Mug'), ('bottle', 'Water Bottle'), ('lamp', 'Desk Lamp'), ('headphones', 'Studio Headphones'), ('clock', 'Wall Clock'), ('vase', 'Ceramic Vase'), ('candle', 'Scented Candle')], max_length=20),
        ),
    ]
